#!/bin/bash

# Seguro Backup Script
# --------------------

# Keeps a small data file of user settings
# Makes simple copies of selected data to defined device
# into a folder it creates, called by the day's date

#
# Variables
#
declare -a LabelArray # Labels require an array as they may be several words with spaces
declare -a PathArray  # Use an array for filepaths also, to allow matching
Passed=" - Feliz Simple Backup Utility - "

#
# Functions
#

MainMenu() {
  Exit="No"
  until [ $Exit = "Yes" ]
  do
    dialog --backtitle "$Backtitle" --title " Feliz Backup Utility " --no-shadow --ok-button "Select" --cancel-button "Quit" --menu "\nWelcome to the Feliz Backup Utility\n" 15 40 2 \
    "Settings" "View and change" \
    "Run" "Choose and run" 2> seguro.output
    if [ $? -gt 0 ]; then # 'Quit' selected
      rm seguro.output
      exit
    else
      Selected=`cat seguro.output`
    fi
    case $Selected in
    "Settings") OpenDataFile    # Open existing file and extract data to arrays
          DisplayDataFile       # Display settings and enable change any details
     ;; 
    *) BackupCheckList # Display sources checklist ()
      if [ $Exit = "Yes" ]; then
        Exit="No"
      else
        Precheck # Checks that destination is ready before calling ActionBackup ()
        Exit="No"
      fi
    esac
  done
}

#
# Data file handling
#

CheckDataFile() {  # First check if data file exists
if [ ! `ls -f seguro.data` ] || [ -z $seguro.data ]; then # No data file, or empty
  NewDataFile="Yes"
  Exit="No"
  until [ $Exit = "Yes" ]
  do
    # Inform user
    dialog --title " - First - " --clear --msgbox "This appears to be the first time Seguro has run on this machine. Before you can make any backups, you will have to set a destination device and at least one source." 10 45
    DestinationPath # Choose destination device
    # Create new data file and save destination
    echo "Destination${DestinationPath}" > seguro.data
    AddSource # Add a source path and label
  done
fi
}

DestinationPath() { # Choose destination device
  UserName=`whoami`
  Message="Choose a destination path for your backups."
  Exit="No"
  until [ $Exit = "Yes" ]
  do
    listgen1 "External Local" " Destination " "" # Present list of all devices
    RetVal=$?
    if [ $RetVal -gt 0 ]; then # Test for <Cancel>
      Exit="Yes"
      break
    else # Here the user has chosen only whether to use an external device or a local one
      Selection=`cat seguro.output` # Recover the selection
      case $Selection in            # Use it to set the startpath
      "Local") StartPath="/home/$UserName"
      ;;
      *) StartPath="/media/$UserName"
      esac
    fi 
    Browse=`ls $StartPath/`
    ListPaths  # List available paths on either external or local
  done
}

ListPaths() { # When user selects one, create a new seguro.data file with device
  until [ $Exit = "Yes" ]
  do
    listgen1 "$Browse" " Destination " "" # Present list of all devices on chosen path
    RetVal=$?
    if [ $RetVal -gt 0 ]; then # Test for <Cancel>
      Exit="Yes"
      break
    else
      Picked=`cat seguro.output` # Recover the selection
      dialog --title " - Destination - " --clear --yes-button "Use" --no-button "Deeper" --extra-button --extra-label "Directory" --yesno "Use device '$Picked' or select a directory from that path?" 10 45
      RetVal=$?
      case $RetVal in
      0) DestinationPath="${StartPath}/${Picked}/" # ie: Yes - finish with selected $StartPath
        Exit="Yes"
        ;;
      1) # Cancel button
        Exit="Yes"
        continue
        ;;
      *) # ie: No - offer directories until done
        StartPath="${StartPath}/${Picked}/"
        Browse=`ls ${StartPath}`
        continue
      esac
    fi
  done
}

EditDestination() { # Edit existing destination
  # Build a list of available devices
  UserName=`whoami`
  Existing=`cat seguro.data | grep Destination`
  DestinationPath # Returns full path in $DestinationPath
  # Overwrite the existing entry in seguro.data file
  sed -i "/Destination/ c\Destination${DestinationPath}" seguro.data

read

}

AddSource() { # Create a new source path
  UserName=`whoami`
  Local=`ls ~/`
  StartPath="/home/$UserName/"
  Message="Choose a file or folder to add to your data file."
  FirstLevel="Yes"
  Exit="No"
  until [ $Exit = "Yes" ]
  do
    listgen1 "$Local" " - Sources - " ""
    RetVal=$?
    if [ $RetVal -gt 0 ] && [ $FirstLevel = "Yes" ]; then # Cancel selected on first level
      Exit="Yes"
    elif [ $RetVal -gt 0 ]; then # Cancel selected on subsequent level
      FirstLevel="No" # Return to previous level
    else
      Selection=`cat seguro.output`
      Path="$StartPath$Selection"
      StartPath="$Path/"
      dialog --title " - Sources - " --clear --ok-label "Save" --extra-button --extra-label "Deeper" --yesno "Save '$Path' to your sources paths, or open it to go deeper? Choose <Cancel> if you wish to do nothing." 10 45
      case $? in
      0) SelectedPath="$Path"
        Message="Enter a short name for this source\n(up to three or four words is best, preferably not more)"
        EditLabel # Enter a label to $SelectedLabel
        if [ -n "$SelectedLabel" ]; then
          # Save new record
          echo "$SelectedLabel$SelectedPath/" >> seguro.data
          Exit="Yes"
        fi
        ;;
      3) Local=`ls $Path` # Offer directories until done
        ;;
      *) SelectedPath=""
        Exit="Yes"
      esac
    fi
  done
}

EditOrDelete() {   # yes/no dialog with options to <Edit> or <Delete> using $SelectedPath & $SelectedLabel
  dialog --title " - Edit or Delete - " --clear --ok-label "Edit" --extra-button --extra-label "Delete" --no-button "Cancel" --yesno "Selected path is '$SelectedPath $SelectedLabel'\n Edit the label, or delete this record?" 10 45
  Action=$?
  case $Action in
  0) EditSource
  ;;
  3) DeleteSource
  ;;
  *) return # Cancel
  esac
}

EditLabel() { # Form to edit an existing or new label
  # Returns $SelectedLabel if completed
  dialog --title " - Sources - " --inputbox "$Message" 16 51 2> seguro.output
  RetVal=$?
  case $RetVal in
  0) SelectedLabel=`cat seguro.output` # 
  ;;
  *) SelectedLabel=""
  esac
}

EditSource() {  # Edit the label of an existing source using $SelectedPath & $SelectedLabel
  # Called via EditOrDelete from DisplayDataFile
  Message="This source is currently labelled '$SelectedLabel'\nEnter a new short name for this source (up to three or four words is best, preferably not more) or <Cancel> to leave it as it is"
  EditLabel # Re-sets $SelectedLabel
  # Then assemble the new label with the path, and replace the record
  Replacement="$SelectedLabel$SelectedPath"
  # Get record number of selected item
  ReadRecord=`cat -n seguro.data | grep ${SelectedPath}$ | awk '{print $1}'`
  # Replace the selected record number with new one
  sed -i "$ReadRecord d" seguro.data # Delete existing record
  echo "$Replacement" >> seguro.data # Append new one
}

DeleteSource() {  # Delete an existing source using $SelectedPath & $SelectedLabel
  # Called via EditOrDelete from DisplayDataFile
  # Get record number of selected item
  ReadRecord=`cat -n seguro.data | grep ${SelectedPath}$ | awk '{print $1}'`
  # First confirm delete
  dialog --title " - Confirm - " --yesno "Are you sure you want to delete this record?" 10 45
  # Then delete it
  sed -i "$ReadRecord d" seguro.data # Delete existing record
}

OpenDataFile() { # Extract records from existing file into arrays
  # Called by almost all routines
  # Count number of lines
  HowMany=`cat -n seguro.data | awk '{print $1}' | tail -c -2`
  # Copy each line into array. Line consists of a label and a filepath
  # There are no spaces between the label and path
  declare -a ItemsArray
  Count=1
  until [ $Count -gt $HowMany ]; do
    ItemsArray[${Count}]=`sed -n "$Count p" seguro.data`
    Count=$((Count+1))
  done 
  # Separate labels from filepaths
  ListofPaths="" # String array to pass list of filepaths to listgen2
  for ((Count=1;Count<=$HowMany;Count++))
    {
    # 1) Label
    Label=`echo ${ItemsArray[${Count}]} | cut -d / -f 1`
    LabelArray[${Count}]="$Label"
    LengthOfLabel=${#Label}
    LengthOfLabel=$(( LengthOfLabel +1 ))
    # 2) Path
    FilePath=`echo ${ItemsArray[${Count}]} | cut -c ${LengthOfLabel}-`
    PathArray[${Count}]="$FilePath"
    ListofPaths="$ListofPaths $FilePath" # For menu display
    }
}

DisplayDataFile() {  # Display existing settings and add, delete or change any details
  Exit="No"
  until [ $Exit = "Yes" ]
  do
    # Call menu dialog to display all items - a) Destination; b) Sources
    Message="\nHere are all your current backup settings ...\nYou can <Select> one to edit or delete, or you can <Cancel> to quit or <Add> to add a new source."
    listgen2 "$ListofPaths" " - Current Settings - " "add" "LabelArray"
    RetVal=$?
    case $RetVal in
    1) Exit="Yes" # ie: Cancel button selected (no action)
      continue
      ;;
    2) AddSource # ie: Add button selected (add a source path)
      ;;
    *) SelectedPath=$(cat seguro.output) # ie: Edit button selected - item to be edited or deleted
      Counter=1                    # Prepare to edit or delete
      for i in $ListofPaths
      do # Match filepath output from dialog with its counterpart in LabelArray
        if [ $i = $SelectedPath ]; then
          SelectedLabel="${LabelArray[${Counter}]}"
          break                    # Record retrieved, so move on
        fi
      done
      # Appropriate action dialog
      if [ $SelectedLabel = "Destination" ]; then
        # Special action dialog for Destination - only allows change
        NewDataFile="No"
        EditDestination
      else # ie: This is a source
        EditOrDelete # Pass this record to decision dialog using $SelectedPath & $SelectedLabel
      fi
    esac
  done
}

#
# Listgen functions
#
listgen1() { # Prepare single-column list
  local Backtitle="$Passed"
  local Title="$2"
  if [ $3 ]; then
    case $3 in
      "nocancel") CancelButton="--nocancel"
      ;;
      *) CancelButton="--cancel-label $3"
    esac
  else
    CancelButton=""
  fi
  local Counter=0
  declare -a Options
  if [ ! $Width ]; then
    Width=40
  fi
  # Prepare $1 for dialog menu
  for item in $1 # Prepare string array of list items passed as $1
  do
    Counter=$((Counter+1))
    Options[${Counter}]="$item"
    Counter=$((Counter+1))
    Options[${Counter}]="-"
    Length=`echo ${#item}`
    if [ $Length -gt $Width ]; then
      Width=$((Length+20))
    fi
  done
  NoTag="--no-tag"
  Printit
}

listgen2() { # Prepare dual-column list
  local Backtitle="$Passed"
  local Title="$2"
  if [ $3 ]; then
    case $3 in
      "nocancel") CancelButton="--nocancel"
      ;;
      "add") CancelButton="--help-button --help-label Add"
      ;;
      *) CancelButton="--cancel-label $3"
    esac
  else
    CancelButton=""
  fi
  declare -a Options
  local Counter=0
  for item in $1; do
    Items[${Counter}]=$item
    Counter=$((Counter+1))
  done
  Counter=0
  local ItemCounter=0
  # Import the complex array
  name=$4[@]
  LongName=("${!name}")
  if [ ! $Width ]; then
    Width=50
  fi
  # Prepare $1 and $4 for dialog menu
  for item in "${LongName[@]}"; do
    Options[$((Counter))]="${Items[${ItemCounter}]}"
    Options[$((Counter+1))]="$item"
    Counter=$((Counter+2))
    ItemCounter=$((ItemCounter+1))
    Length=`echo ${#item}`
    if [ $Length -gt $Width ]; then
      Width=$((Length+30))
    fi
  done
  NoTag=""
  Printit # The final frontier
}

Printit() { # Display the list prepared in listgen1 or listgen2
  Counter=$((Counter/2))
  # Calculate number of lines
  echo $Message > seguro.output
  countcharacters=`cat seguro.output | wc -c`  # Count number of characters in $Message
  countlines=$((countcharacters/Width)) # Calculate lines
  echo $Message | sed 's/[^\\]//g' > seguro.output   # Use sed to remove all except newlines
  countnewlines=`cat seguro.output | wc -c` # Count newline characters
  Height=$((countlines+countnewlines+Counter+16-Counter))
  if [ $Height -gt 19 ]; then
    Height=19
    if [ $Width -lt 50 ]; then
      Width=$((Width+10))
    fi
  fi
  # Use $Counter and ${Options[@]} array in dialog
  dialog --backtitle "$Backtitle" --title " $Title " --no-shadow --ok-button "Select" $CancelButton \
      --menu "$Message\n" $Height $Width $Counter "${Options[@]}" 2> seguro.output
}

#
# Operational
#

BackupCheckList() { # A dialog checklist of saved sources.
  # User can check/uncheck items before proceeding to run backup
  OpenDataFile # 1) Rebuild list of names to be sure it's up-to-date
  # Prepare for display
  local Counter=1
  LineCounter=0
  declare -a Options
  # Prepare Options array for dialog checklist
  until [ $LineCounter -eq $HowMany ]
  do
    LineCounter=$((LineCounter+1))
    if [ "${LabelArray[${LineCounter}]}" != "Destination" ]; then
      Options[${Counter}]="${LabelArray[${LineCounter}]}"
      Counter=$((Counter+1))
      Options[${Counter}]=" "
      Counter=$((Counter+1))
      Options[${Counter}]="on"
      Counter=$((Counter+1))
    fi
  done
  # User selects from checklist
  dialog --backtitle " - Seguro Backup - " --title " - Run backup - " --separate-output --checklist "Select which items to backup using this list.\nPress SPACE to toggle an item on/off" 20 61 5 \
        "${Options[@]}" \
        2> seguro.output
  RetVal=$?
  if [ $RetVal -gt 0 ]; then      
    Exit="Yes"
  fi
}

Precheck() { # Check that destination is switched on before starting action
  Exit="No"
  Target="No"
  until [ $Exit = "Yes" ]
  do
    TestDestination
    if [ $Target = "Yes" ]; then
      ActionBackup
      Exit="Yes"
    fi
  done
}

ActionBackup() { # Retrieve items and copy sources to destination
  HowMany=`cat -n seguro.output | awk '{print $1}' | tail -c -2`
  # Go through the list of selected items, checking label against $LabelArray
  # and getting record number to retrieve path from $PathArray
  Counter=1
  until [ $Counter -gt $HowMany ]
  do  
    item=`cat -n seguro.output | grep $Counter | cut -c 8-`
    Count=1 
    until [ $Count -eq $HowMany ]
    do
      Retrieve=$((Count+1)) # Use item number in the arrays, ignoring Destination
      if [ "${LabelArray[${Retrieve}]}" = "$item" ]; then # Item matches $LabelArray
        ItemPath=${PathArray[${Retrieve}]}                # Find same number in PathArray
        cp -r $ItemPath $Destination$Today/
        break
      fi
      Count=$((Count+1))
    done
    Counter=$((Counter+1))
  done
}

CheckTarget() { # Checks in case target folder and files already exists
  if [ ! -d "$saveto" ]; then
    mkdir "${saveto}"
    echo "Copying files from $savefrom to $saveto"
    cp -a ${savefrom} ${saveto}
  else
    read -p "Files already exist in target directory $Target1. Overwrite? (y/n) : " Response
    case $Response in
      "y" | "Y" | "") echo "Copying files from $savefrom to $saveto"
          cp -a ${savefrom} ${saveto}
        ;;
      *) echo "Not copying"
    esac
  fi 
}

TestDestination() { # Checks that destination device is available
  Exit="No"
  until [ $Exit = "Yes" ]
  do
    Destination=`cat seguro.data | awk '{print $1}' | cut -c 12-`
    Target=`ls $Destination` # Check that it is turned on
    if [ -n "$Target" ]; then
      Today=`date +%F`       # Today's date
      Target1=`ls $Destination | grep ${Today}` # Check for existing backup
      if [ -z "$Target1" ]; then
        mkdir $Destination$Today # Make dated directory on destination device
      fi
    else
      while [ -z "$Target" ] # Destination is not available
      do
        dialog --title " - Not ready - " --clear --yesno "The destination device appears to be turned off. Please turn it on. Try again?" 10 45
        if [ $? -eq 0 ]; then
          Target=`ls $Destination` # Try again
        else
          Target="Yes"
          Exit="Yes"
          break # Quit this function
        fi
      done
    fi
  done
}

#
# Execute
#

CheckDataFile # First check if data file exists, and if not create it

# Let's have a main menu in this one!!!
MainMenu

